version: '3.9'
services:
  nginx:
    image: nginx:1.25-alpine
    ports: ['8080:80']
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/public:ro
      - ./app:/var/www/app:ro
      - ./vendor:/var/www/vendor:ro
      - ./public/assets:/var/www/public/assets:ro
    depends_on: [php]
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db
      DB_NAME: career_rec
      DB_USER: root
      DB_PASS: example
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: career_rec
    ports: ['3306:3306']
    volumes:
      - dbdata:/var/lib/mysql
  ml:
    build: ./ml
    ports: ['5000:5000']
  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ['9090:9090']
  grafana:
    image: grafana/grafana
    ports: ['3000:3000']
volumes:
  dbdata:
